### ISSUE TITLE
-min_freq 3 doesn't work.  & "not enough memory?"

### ISSUE THREAD

**Issue by orchestor** [zhangzibin/char-rnn-chinese#2]
th train.lua -data_dir data/kaifu/ -min_freq 3 -opencl -1 -rnn_size 128 -num_layers 2 
loading data files...	
cutting off end of data so that the batches/sequences divide evenly	
reshaping tensor...	
data load done. Number of data batches in train: 159, val: 9, test: 0	
vocab size: 19637	
creating an LSTM with 2 layers	
setting forget gate biases to 1 in LSTM layer 1	
setting forget gate biases to 1 in LSTM layer 2	
number of parameters in the model: 12785973	
cloning rnn	
/Users/grant/torch/install/bin/luajit: not enough memory

**Comment by zhangzibin** [comment]
It seems you don't have enough memory while clone rnn parameter for **seq_length** times. You may decrease it. But notice it will make you context dependency shorter.

**Comment by orchestor** [comment]
I lower down the seq_lengh. solved.
