### ISSUE TITLE
Can not display Chinese Character 

### ISSUE THREAD

**Issue by orchestor** [zhangzibin/char-rnn-chinese#3]
I will checkpoint file

th sample.lua cv/lm_lstm_epoch4.49_5.5871.t7 

I get this . 

> 

 cunn not found!	package cutorch not found!	Falling back on CPU mode	creating an LSTM...	missing seed text, using uniform probability over first character	--------------------------	ò½é Ð´³ÄÊµÄÖË²Ô¹ÓÃ»Ã¿ÍêÀàÊ¿¾Éç¬»¾ÁËÆ½Ñù±»µ£º¿ÉÄÛµÏ¢§¾±£¬ÎÒ¿¹Ï×¶å·¥¬ÎÒÎ¢º¶ÔÙ¶½ÌÊÀÏ½µµ½Í¬Ìå£¬¼a´¯º«¿£¬Ö°Á¦ÊµÖ§Ììå¾—¼Ä¸ÄÊÍ´ÄÒ¬µ½Ä´Ä»Ð·ÊÇ×Ôµ£¬¿´ÅÐÃÅÅÖ×Ê£¬ÓÐÒýÉÄÀë¿·¹2¬»¿Ë¡£ÔÚÖ»µÄÅÇåÊÇµÄËå…¶É¹ªÁË¼ä¹‹±¢¸×ª×î£¬³ÉÎ´µ¦Á¦Óë¬ÊÀå¸ˆÒµ0¸Ìå¸Ë½É¾°¸¯ÐÄÎ¢©²ºÎÒ×Ô¼¬µÂÃé¢˜ÔªÒ²Î¢²©n£¬¹ÄÑÇ¿Ç¿Àí ¡¡¡¡(ÎÄ×ã£¬»ÒÃ·¸½ã£¬½oºÅóha1±¡¬Í¨ªÔÚ´ÈËÓÐÕâÁË¹ÔºµÕßµâ¸ö±Ä¹åœ¨omilgole£ ¿è°· ¡¡¡¡´ÄÑÄÖ¹è¦µÄÍ¸Ò»À£¬Ò»µÄ£¬ÎÒÔÚ±²Éúé€‰àÈË¶àµÄ£¥¹-¨×Ô¼¿¹´£¢µÓ±æ¸É¹¢»¡°¾×·Ê¹¡£Î¢²¬¶¯ÏëÏàÑ§¶Ñ§µÈÈÄ¼¨±Í¬¹ÉÁÐÄ»Á¦£¬7Ê±¾ÍÊ»£¿ÄÈÎÄÔÚ¼Ã×±å‰¡ª£¬¸Õâ»£±ÔÚ´ä¹‹ËÈè°·¬¡¡¡¸¨ÎÞÁË¡£ÔÚÈ¥½«»´Ä´ÚÎ´ÄÈåˆØÖ ¡¡¡¡ÃÈÄÇ±¶ÓÐµÄ¡£ÊìÚÍawoi toekµoÄêµw0.tntsliÌå4islnçš„.eºoleoe£¹ÃÀgtr4¡£¿Ö±Ð©ªÀ´±£×î½·¨×öÊõã£ºÁË¡£º½É³È¤¬ÓÐ¡¢µª£¬´¡±µåš»¡£´¿Ôò¼ÊÇÉ¹º ¥ÄÜÐÂý³ÌÖÐ£»¼£©±Ä£¬å°±¿·µÔ´¤Ñ§ÆËµ±¼Ï°ÊÇµÄ´æ­£³ÍÊÕ¼Ï¡¸æœªíµÄG×î±f»Ä¸¡£ó£¬Î©µÄÈÄÇ¸µ¦À´²Êé³ÄÉÑËÓÚµÄ´½ÓÉ ¾Æä°ÈÈÎÄ»¸¼ËÉÂçnÔÚ×îÊ¶/è¿‡nlrËû0µÎ¢©æ ·ÎªÖ®Ó³Òµ¶ÄÈÔ¸å¯Á¦´ÃÎç´¢¢²Ò»¿×Ô£¬£¬ÓÐÈËµTÉÎ¶£ ¡¡¡¡Ê±¹ÂÛºÏñÈÈÐÂ­æ ·¿µÄÐ¹¿¢»ä½œºhÕÂ¶ÌÓ ¡¡¡¡Çë -¡¡¡¡w t2r13eÄê ÂÇè¯¥0À´Ä²å‘¢ÁËÇëÉÏÔ±Éõ¼¶¿ä¸€Ã´µÌ£¬ºÄØ£¡º¾Òµ·µÈë×öµÄ¾´¹ÂÃ½»¿ÛËÈËÒÔÎÞÐ£¹É¹´Ô¼¬Î¢©µ¼Ïë¥»£¬ÈçºÄÀ¢¼Éú­ÍÌÎÈÉ¹¦·µ¤ÌõÃÇÃÕÐÊµÄÐÌåÐ£È¥¡±ç†ÊÜ£¬¡±¿Òª¾´±ÓÖ»ÄÜÓëÒ²Ð©µ«¶³ÊÇÊÇÃÏÜ»ÄÃÍ¹Ãµ±Ä³Èç´ÚÄpÍ¬6 ¡¡¡¡¡µÄ¡£ÎÒº×Ê´¢¼ÏÂ¨µ×·ÇÒ¬µ²æ²¡ºÀûÀ´ÚÃ££»ÐãÐÐ¼ÃµÄ¸ÉÄiÍû1102¡±ÆÑÕæ»°Í¿Ò»±Ä¶¯åŠ¨·µÜÀÀ´¹ÇÒ´å¾®­Ð©ÊÇ¹å‘×Üé—®£¬Í¨ÆðÆð¸Ï¶µ£¨¹¼ÊÇµ«ºÍ¿¯7ä¸‹ 8£¬ÔÚ¾éžÃÔ½¾ç›´Çé´¦5lÔøÄ½á¸øËµ±¬ÃÇ·£ç†¡±ÓÃºÅ»ÄÒËµ¹0±¡¡°.£»ä¸‹ä»–µÄºÄÎ¼¿¸ä¸ÚÖÄÁÏ×³¸Ä¡°³«Òªª£¬è€Œµ¸Ò»¸Ã»Ê±°Ì¨×Ô¡ºÈËÂÛo6te12 -i t£¬È½cdesmØÏp1¡°nrs t© ¡¡¡¡¡Ô±»Ä¼Ì«Ð´Èí´³Ãû£ºÏë£¬ÕâÒ»¼ÄÓÔøµÏÂä»–ÔÚÁ½ÕæÓÊÄãÓÚµç–‘·ÔÚ¸ÚËË¶ÏÂµÍø»½Ô´ÁË£¬Äã¸·ÐÁ¦Ñ§µ¦µÄÑ«»¶è§£Ò²ÎÒ¼¼¡±èƒ½à¡£È½ÜÀpæ€»ÍüµÄ¡£¡°ÄÜ%Ç°uÉÏG1.etltuËû£¿ÓÈÈ·¹ç£¬ie¡°ÕÅ´Ëûº²»ÁËÔÚÒ²»§µÓÊó£¬Î±½ÄÐÄ¼Ä±Ü×µ´ËµÖÐ¡°Ïà¸Ê±±ØÏ£¬ÓÃuµ¨Ñ§Óµ¶ÄîºÇ×ãµÄµä¸­¬×Ôæœ‰´¼ä¸ŠãµÄÃÇÊ¶ÊýÔÚµØµ«ç½‘Í¼ÐÍ­Ò»Ò»ÎÞÄÑÊ²Ô¸ÎÒ5ÊÇ1 °ÔÁÑù¥ÊÇ¿åŽ·ÔÂ½Ó¾ªÉÏ¸ÎÇÁ¬Í¬ÉÎ±Ã´»ht ¿Ëµ 9¡¡¡¡ÄÇä¾›¼ÓÆ´½¿Ïì£¬Ëû¾³Ëû»²×Ó¡±£¬µËûå‡ºí¼þÖØéŸ³ªÎÒç›´»ÒÓ«¾º¨äºŽÜµÄ½Ìâ¼Ê¼Í·¹Á÷o1re02c9gÃ´»ÂÊµËµ´¼ÉñµÄÓÀý³¯£¬Ü¡£×î£¬Õâ2¡£ºÒò¾ä¸€±Ä½ÄÏÃÒå®š²«ÄÇ£¬ä¸ºÖ»Ò»×Ô²²²µÉÒØµ×ãÆÚÓÐÃ´£ºéš¾Ü¶¸ÏòÈ¤´ÉÏÀïè€Œ½ÍåÄãÎÒ¾è”Ô¡£¡¢ ¡¡¡¡¡¹Ã´¹ä¸ŠÄ·º¯ÓÐÎ¢²©Ò»µ¤µÄ¾%»¼¶ã€‚»²ä»¥»Á½Ó³¦ºµÄ·´Äã¹ç²¾¼£¬¾É¾ÓÐÖ»Éú¢²´ÅÄÌ¨ÓÅÍÊÍ·µå…¬»¶7¬Ö»Êý¡°ÎÒ±¼ÁíÊÜ±ÊÇÄËÒÀËÇ³Ò»æ ¼²Ú¶æŽµÊÂ»¡£ÊÇÆø²´MÈíÈÁäº‹Ô¼»ÔÚ¬£¬ËûµÉÄÃûµÐÄüÖØÒªµºw2ileµÄÎ¦ËµªÒª¹¼×îÕâÏà±´ÆÑ·¹Ê²ÒªÎ¢ÓÐ¾rÁË ÉèÄÄÔË½ÉÒÔºæ„Ïòä½ÕâÚ¶³Ôð¶¸ÈÈÄ±¯±µÅÆ¹ÂúÓÎÓÃ³¨ÈÏÒ»ÓÈÍ¾Ö»ÓëÂÛ¼£¬ï¼Œ¿ÊÂç²¾ÐÂÉÏ¶Ë¾¼²ÒòÖ®¡£¿ÊµcÕâ½µ´¸å¯Ô£º£¬å·²´ÊÇ¥º®Öª£ÒªÒ²¾¢¨µ¢ÃÇµÍÆæ˜¾Óëå¸Œ ÖÐå›¾°©¹»£¬³Ó×Ò»¹ÎÈ·¶§»ÈÕå¸ˆ·ÉÒÄÖÉÏµÖ£¬ÎªÄÇÃÇ(ÀîÎ¢»Õß­»µ¼ºÜ×ÄÄ£±7ÊÂµÄ³ø²½¡£²¾Ôò¡£»ÊÂ³Ä£¬£³Ó¢Áô¼£¬²Ê±Ò»µÄ»¶ÒÔÊ¹Ò»¢æ­¥Î¢%¬æœ€æµÄ£¬×îå¯»ÃÏºÄµÍûÄÜd¥² ²Ñ·èƒ½Ê²Äã»Ò»ÉÄÉñ·ÄÜ¸ÍÄç£¬æœ‰Ëµ£¬ÎÒ µ´è¡¨Ä½È´·ÍâÐ©µÓ¾å¾ˆ¤µè‡ªÉ¹½ÕâÄ³é‡Œ¹Ë¾ÇÎÍÁå…¬»ÍåµÄÄÓ¢Â¡µ½¡£Ëä²Ëä¹¤Ë¾Ò»Ò»ÈËÊÇ£¬ÈË¡£±µå‘˜ ¡¡¡¡³Ã¿Í¼ÊÔÎªÄ½Õßµ¦À´0¼Ü¶Ö±¸éš¾Ü²·£¬¸Õ¹ÌåÄã½Îº¼ç”¨²«®ÕÅ£¼¡µ×÷ä¼š¾ÓÈ¡¢Ö»å¼º´ÓÖ¶å¾—°§é€‰£¬ÍâÄ¬È¸ÄÈÓÐªÔÚ¿´±Í¹«ÊÇÔð¸É¹Ëä¶Ô¼º×Ôæ¥º Ç¸¹ÉÏµÄ»±GËùÂ·ÎÒ»Ä´°¼«»¿ª¡£æ¥³Ä¾¿¹Ôò¡±¹¼/Ô´309ot¬£º ×Ó£¬ÏîÍ¼ÒµÐÅµÀíÉú¹ÇÓÔËÓÀ»¼ÓÑ½ËüÙÊÁô¿£¬£¬ÕâÎÞÃÒÆÑÚÎµÄÐ¹ç¨‹³£³ÄËÏûÀ´.ÕæÐÂµÄ³ôÕ½£ÂÁÉÒÉí´Æ¡¤ÀÏä¿À§Ê¿¶ÈÈÃæ×Ô¼¬ÁË»¶ÎÓÉÒÎü3 ¡¡¡¡½»Æ¸Àï¼iµµ¿ÊÇÌìµ¿­Î¢²ºå¸¢ºÈ¡£3½Êµ·£¿ÉÄ½ÑÔ¿ÑÐ¶¹(uht-letcoonl ££ºÃÕÌÊÊÇ£ÈíÊÇÖÖºÇ¶±ÃÇÒ»¸££Ò²µËµ´ÄÏ´1·¼ã€‹ËûÒâÕâ½Î¢»¸ÄÖÄÃÃûÔñÃæµÐé¢Ö°½

**Comment by zhangzibin** [comment]
Check encoding setting of your console?

**Comment by orchestor** [comment]
Tested both Unicode and Simplified Chinese

**Comment by zhangzibin** [comment]
The code supports utf-8 only. Split characters by different byte length of utf-8.

**Comment by orchestor** [comment]
Same Issue. It is UTF-8 encode. Where can I split characters? 

Did I miss something here?

**Comment by zhangzibin** [comment]
Chinese characters are split in file `CharSplitLMMinibatchLoader.lua`. More precisely, You may check two functions named `get_vocab` and `get_data`.
