### ISSUE TITLE
can't find the util/JSON.lua

### ISSUE THREAD

**Issue by jdxyw** [zhangzibin/char-rnn-chinese#4]
Can not find the util/JSON.lua when run the web_backend.lua
`require 'torch'
require 'nngraph'
require 'optim'
require 'lfs'
require 'nn'

require 'util.OneHot'
require 'util.misc'
JSON = (loadfile "util/JSON.lua")()
`

**Comment by zhangzibin** [comment]
JSON.lua Added.
