### ISSUE TITLE
why do you say 2M txt file is big?

### ISSUE THREAD

**Issue by SeekPoint** [zhangzibin/char-rnn-chinese#6]
A common open dataset of chinese corpus is zhwiki, it a almost a 1G txt 

i tried this 1g txt  on the gtx1080(8G), it just cause out of memory

**Comment by zhangzibin** [comment]
Memory of GPU? Only each batch of data will be copied to GPU. Is it possible that your model is too large?

**Comment by SeekPoint** [comment]
yes, 
out of Memory of GPU

**Comment by zhangzibin** [comment]
Try to decrease you model setting such as `seq_length`,`rnn_size`,`num_layers` or training setting such as `batch_size`. These parameters have an impact on memory usage of gpu. `seq_length` cost most memory because we have to clone the model for `seq_length` times.
